/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kiwiple_mhk_filter_NativeImageFilter */

#ifndef _Included_com_kiwiple_mhk_filter_NativeImageFilter
#define _Included_com_kiwiple_mhk_filter_NativeImageFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kiwiple_mhk_filter_NativeImageFilter
 * Method:    curveProcessing
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;II[S[S[S[S)V
 */
JNIEXPORT void JNICALL Java_com_kiwiple_imageframework_filter_NativeImageFilter_curveProcessing
  (JNIEnv *, jclass, jobject, jint, jint, jshortArray, jshortArray, jshortArray, jshortArray);

/*
 * Class:     com_kiwiple_mhk_filter_NativeImageFilter
 * Method:    contrastProcessing
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IIF)V
 */
JNIEXPORT void JNICALL Java_com_kiwiple_imageframework_filter_NativeImageFilter_contrastProcessing
  (JNIEnv *, jclass, jobject, jint, jint, jfloat);

/*
 * Class:     com_kiwiple_mhk_filter_NativeImageFilter
 * Method:    brightnessProcessing
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;III)V
 */
JNIEXPORT void JNICALL Java_com_kiwiple_imageframework_filter_NativeImageFilter_brightnessProcessing
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     com_kiwiple_mhk_filter_NativeImageFilter
 * Method:    textureProcessing
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;III)V
 */
JNIEXPORT void JNICALL Java_com_kiwiple_imageframework_filter_NativeImageFilter_textureProcessing
  (JNIEnv *, jclass, jobject, jobject, jint, jint, jint);

/*
 * Class:     com_kiwiple_mhk_filter_NativeImageFilter
 * Method:    getSpline
 * Signature: ([S)[S
 */
JNIEXPORT jshortArray JNICALL Java_com_kiwiple_imageframework_filter_NativeImageFilter_getSpline
  (JNIEnv *, jclass, jshortArray);

/*
 * Class:     com_kiwiple_mhk_filter_NativeImageFilter
 * Method:    grayProcessing
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_kiwiple_imageframework_filter_NativeImageFilter_grayProcessing
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     com_kiwiple_mhk_filter_NativeImageFilter
 * Method:    saturationProcessing
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IIF)V
 */
JNIEXPORT void JNICALL Java_com_kiwiple_imageframework_filter_NativeImageFilter_saturationProcessing
  (JNIEnv *, jclass, jobject, jint, jint, jfloat);

/*
 * Class:     com_kiwiple_mhk_filter_NativeImageFilter
 * Method:    allocByteBuffer
 * Signature: (I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_kiwiple_imageframework_filter_NativeImageFilter_allocByteBuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_kiwiple_mhk_filter_NativeImageFilter
 * Method:    freeByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_kiwiple_imageframework_filter_NativeImageFilter_freeByteBuffer
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
