/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kiwiple_multimedia_audio_BeatTracker */

#ifndef _Included_com_kiwiple_multimedia_audio_BeatTracker
#define _Included_com_kiwiple_multimedia_audio_BeatTracker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kiwiple_multimedia_audio_BeatTracker
 * Method:    nativeTrack
 * Signature: ([SI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_kiwiple_multimedia_audio_BeatTracker_nativeTrack
  (JNIEnv *, jclass, jshortArray, jint);

#ifdef __cplusplus
}
#endif
#endif
