/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kiwiple_multimedia_canvas_PixelUtils */

#ifndef _Included_com_kiwiple_multimedia_canvas_PixelUtils
#define _Included_com_kiwiple_multimedia_canvas_PixelUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kiwiple_multimedia_canvas_PixelUtils
 * Method:    nativeResizeBilinear
 * Signature: (JJIIFFF)V
 */
JNIEXPORT void JNICALL Java_com_kiwiple_multimedia_canvas_PixelUtils_nativeResizeBilinear
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jfloat, jfloat, jfloat);

/*
 * Class:     com_kiwiple_multimedia_canvas_PixelUtils
 * Method:    nativeResizeNearestNeighborYUV
 * Signature: (Ljava/nio/ByteBuffer;[BIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_kiwiple_multimedia_canvas_PixelUtils_nativeResizeNearestNeighborYUV
  (JNIEnv *, jclass, jobject, jbyteArray, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_kiwiple_multimedia_canvas_PixelUtils
 * Method:    nativeApplySplitTransition
 * Signature: (JJJIIIF)V
 */
JNIEXPORT void JNICALL Java_com_kiwiple_multimedia_canvas_PixelUtils_nativeApplySplitTransition
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jint, jint, jfloat);

/*
 * Class:     com_kiwiple_multimedia_canvas_PixelUtils
 * Method:    nativeApplyLightingEffect
 * Signature: ([I[II)V
 */
JNIEXPORT void JNICALL Java_com_kiwiple_multimedia_canvas_PixelUtils_nativeApplyLightingEffect
  (JNIEnv *, jclass, jintArray, jintArray, jint);

/*
 * Class:     com_kiwiple_multimedia_canvas_PixelUtils
 * Method:    nativeApplyRedLightingEffect
 * Signature: ([I[II)V
 */
JNIEXPORT void JNICALL Java_com_kiwiple_multimedia_canvas_PixelUtils_nativeApplyRedLightingEffect
  (JNIEnv *, jclass, jintArray, jintArray, jint);

/*
 * Class:     com_kiwiple_multimedia_canvas_PixelUtils
 * Method:    nativeApplyCircleLightingEffect
 * Signature: ([I[IIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_kiwiple_multimedia_canvas_PixelUtils_nativeApplyCircleLightingEffect
  (JNIEnv *, jclass, jintArray, jintArray, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_kiwiple_multimedia_canvas_PixelUtils
 * Method:    nativeApplyGrayscale
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_kiwiple_multimedia_canvas_PixelUtils_nativeApplyGrayscale
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_kiwiple_multimedia_canvas_PixelUtils
 * Method:    nativeConvertYuv420pToArgb
 * Signature: ([B[III)V
 */
JNIEXPORT void JNICALL Java_com_kiwiple_multimedia_canvas_PixelUtils_nativeConvertYuv420pToArgb
  (JNIEnv *, jclass, jbyteArray, jintArray, jint, jint);

/*
 * Class:     com_kiwiple_multimedia_canvas_PixelUtils
 * Method:    nativeConvertYuv420spToArgb
 * Signature: ([B[III)V
 */
JNIEXPORT void JNICALL Java_com_kiwiple_multimedia_canvas_PixelUtils_nativeConvertYuv420spToArgb
  (JNIEnv *, jclass, jbyteArray, jintArray, jint, jint);

/*
 * Class:     com_kiwiple_multimedia_canvas_PixelUtils
 * Method:    nativeConvertArgbToYuv420sp
 * Signature: ([I[BII)V
 */
JNIEXPORT void JNICALL Java_com_kiwiple_multimedia_canvas_PixelUtils_nativeConvertArgbToYuv420sp
  (JNIEnv *, jclass, jintArray, jbyteArray, jint, jint);

/*
 * Class:     com_kiwiple_multimedia_canvas_PixelUtils
 * Method:    nativeRotate
 * Signature: ([I[IIII)V
 */
JNIEXPORT void JNICALL Java_com_kiwiple_multimedia_canvas_PixelUtils_nativeRotate
  (JNIEnv *, jclass, jintArray, jintArray, jint, jint, jint);

/*
 * Class:     com_kiwiple_multimedia_canvas_PixelUtils
 * Method:    nativeCrop
 * Signature: ([I[IIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_kiwiple_multimedia_canvas_PixelUtils_nativeCrop
  (JNIEnv *, jclass, jintArray, jintArray, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
