/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kiwiple_mediaframework_ffmpeg_FFmpegProcessor */

#ifndef _Included_com_kiwiple_mediaframework_ffmpeg_FFmpegProcessor
#define _Included_com_kiwiple_mediaframework_ffmpeg_FFmpegProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kiwiple_mediaframework_ffmpeg_FFmpegProcessor
 * Method:    nativeExecute
 * Signature: ([Ljava/lang/String;Lcom/kiwiple/mediaframework/ffmpeg/FFmpegListener;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_kiwiple_mediaframework_ffmpeg_FFmpegProcessor_nativeExecute
  (JNIEnv *, jclass, jobjectArray, jobject);

void onExit(int state);

#ifdef __cplusplus
}
#endif
#endif
